=== grug-lang/grug-tests/mod_api_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "constraints": {
            "$ref": "#/definitions/constraintsObject"
        },
        "entities": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "required": [
                    "description"
                ],
                "additionalProperties": false,
                "properties": {
                    "description": {
                        "type": "string"
                    },
                    "static_methods": {
                        "$ref": "#/definitions/functionsObject"
                    },
                    "methods": {
                        "$ref": "#/definitions/functionsObject"
                    },
                    "export_functions": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": [
                                "name",
                                "description"
                            ],
                            "additionalProperties": false,
                            "properties": {
                                "name": {
                                    "type": "string"
                                },
                                "description": {
                                    "type": "string"
                                },
                                "parameters": {
                                    "$ref": "#/definitions/parametersArray"
                                }
                            }
                        }
                    }
                }
            }
        },
        "classes": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "required": [
                    "description"
                ],
                "additionalProperties": false,
                "properties": {
                    "description": {
                        "type": "string"
                    },
                    "used_generics": {
                        "$ref": "#/definitions/usedGenericsArray"
                    },
                    "static_methods": {
                        "$ref": "#/definitions/functionsObject"
                    },
                    "methods": {
                        "$ref": "#/definitions/functionsObject"
                    }
                }
            }
        },
        "host_functions": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "required": [
                    "description"
                ],
                "additionalProperties": false,
                "properties": {
                    "description": {
                        "type": "string"
                    },
                    "used_generics": {
                        "$ref": "#/definitions/usedGenericsArray"
                    },
                    "return_type": {
                        "$ref": "#/definitions/type"
                    },
                    "parameters": {
                        "$ref": "#/definitions/parametersArray"
                    }
                }
            }
        }
    },
    "definitions": {
        "constraintsObject": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/constraint"
            }
        },
        "constraint": {
            "type": "object",
            "required": [
                "description",
                "implementors"
            ],
            "additionalProperties": false,
            "properties": {
                "description": {
                    "type": "string"
                },
                "implementors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/constraintImplementor"
                    }
                }
            }
        },
        "constraintImplementor": {
            "type": "object",
            "required": [
                "type"
            ],
            "additionalProperties": false,
            "properties": {
                "used_generics": {
                    "$ref": "#/definitions/usedGenericsArray"
                },
                "type": {
                    "$ref": "#/definitions/type"
                }
            }
        },
        "usedGenericsArray": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/genericUsage"
            }
        },
        "genericUsage": {
            "type": "object",
            "required": [
                "name"
            ],
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "constraints": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "functionsObject": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "required": [
                    "description"
                ],
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "used_generics": {
                        "$ref": "#/definitions/usedGenericsArray"
                    },
                    "description": {
                        "type": "string"
                    },
                    "parameters": {
                        "$ref": "#/definitions/parametersArray"
                    },
                    "return_type": {
                        "$ref": "#/definitions/type"
                    }
                }
            }
        },
        "parametersArray": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "name",
                    "type"
                ],
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "type": {
                        "$ref": "#/definitions/type"
                    }
                }
            }
        },
        "type": {
            "type": "object",
            "required": [
                "name"
            ],
            "if": {
                "properties": {
                    "name": {
                        "const": "resource"
                    }
                }
            },
            "else": {
                "not": {
                    "required": [
                        "optional"
                    ]
                }
            },
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "used_generics": {
                    "$ref": "#/definitions/usedGenericsArray"
                },
                "constraints": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "generics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/type"
                    }
                },
                "resource_extension": {
                    "type": "string"
                },
                "optional": {
                    "type": "boolean"
                },
                "entity_type": {
                    "type": "string"
                }
            }
        }
    }
}

=== grug-lang/grug-tests/mod_api.json
{
	"constraints": {
		"Default": {
			"description": "A type where a default value can be created with no inputs",
			"implementors": [
				{
					"type": {
						"name": "number"
					}
				},
				{
					"type": {
						"name": "string"
					}
				},
				{
					"type": {
						"name": "bool"
					}
				},
				{
					"used_generics": [
						{
							"name": "$T1",
							"constraints": [
								"Default"
							]
						},
						{
							"name": "$T2",
							"constraints": [
								"Default"
							]
						}
					],
					"type": {
						"name": "Pair",
						"generics": [
							{
								"name": "$T1"
							},
							{
								"name": "$T2"
							}
						]
					}
				},
				{
					"used_generics": [
						{
							"name": "$T"
						}
					],
					"type": {
						"name": "Vec",
						"generics": [
							{
								"name": "$T"
							}
						]
					}
				}
			]
		},
		"Hash": {
			"description": "A type that can be hashed deterministically",
			"implementors": [
				{
					"type": {
						"name": "number"
					}
				},
				{
					"type": {
						"name": "string"
					}
				},
				{
					"type": {
						"name": "bool"
					}
				},
				{
					"used_generics": [
						{
							"name": "$T1"
						},
						{
							"name": "$T2"
						}
					],
					"type": {
						"name": "Pair",
						"generics": [
							{
								"name": "$T1"
							},
							{
								"name": "$T2"
							}
						]
					}
				},
				{
					"used_generics": [
						{
							"name": "$T"
						}
					],
					"type": {
						"name": "Vec",
						"generics": [
							{
								"name": "$T"
							}
						]
					}
				}
			]
		},
		"Print": {
			"description": "A type that can be printed. Its implementors and Show's refer to each other",
			"implementors": [
				{
					"type": {
						"name": "bool"
					}
				},
				{
					"used_generics": [
						{
							"name": "$T",
							"constraints": [
								"Show"
							]
						}
					],
					"type": {
						"name": "$T"
					}
				}
			]
		},
		"Show": {
			"description": "A type that can be shown. Its implementors and Print's refer to each other",
			"implementors": [
				{
					"type": {
						"name": "number"
					}
				},
				{
					"used_generics": [
						{
							"name": "$T",
							"constraints": [
								"Print"
							]
						}
					],
					"type": {
						"name": "$T"
					}
				}
			]
		}
	},
	"entities": {
		"A": {
			"description": "foo"
		},
		"D": {
			"description": "foo",
			"static_methods": {
				"magic": {
					"description": "foo",
					"return_type": {
						"name": "number"
					}
				}
			},
			"methods": {
				"double": {
					"description": "foo",
					"return_type": {
						"name": "number"
					},
					"parameters": [
						{
							"name": "x",
							"type": {
								"name": "number"
							}
						}
					]
				}
			},
			"export_functions": [
				{
					"name": "a",
					"description": "foo"
				}
			]
		},
		"E": {
			"description": "foo",
			"export_functions": [
				{
					"name": "a",
					"description": "foo"
				},
				{
					"name": "b",
					"description": "foo"
				}
			]
		},
		"F": {
			"description": "foo",
			"export_functions": [
				{
					"name": "a",
					"description": "foo",
					"parameters": [
						{
							"name": "x",
							"type": {
								"name": "number"
							}
						}
					]
				}
			]
		},
		"G": {
			"description": "foo",
			"export_functions": [
				{
					"name": "a",
					"description": "foo",
					"parameters": [
						{
							"name": "x",
							"type": {
								"name": "number"
							}
						},
						{
							"name": "y",
							"type": {
								"name": "number"
							}
						}
					]
				}
			]
		},
		"J": {
			"description": "foo",
			"export_functions": [
				{
					"name": "a",
					"description": "foo"
				},
				{
					"name": "b",
					"description": "foo"
				},
				{
					"name": "c",
					"description": "foo"
				}
			]
		},
		"R": {
			"description": "foo",
			"export_functions": [
				{
					"name": "a",
					"description": "foo",
					"parameters": [
						{
							"name": "f",
							"type": {
								"name": "number"
							}
						}
					]
				}
			]
		},
		"S": {
			"description": "foo",
			"export_functions": [
				{
					"name": "a",
					"description": "foo",
					"parameters": [
						{
							"name": "i",
							"type": {
								"name": "number"
							}
						},
						{
							"name": "f",
							"type": {
								"name": "number"
							}
						}
					]
				}
			]
		},
		"T": {
			"description": "foo",
			"export_functions": [
				{
					"name": "a",
					"description": "foo",
					"parameters": [
						{
							"name": "timer",
							"type": {
								"name": "Timer"
							}
						}
					]
				}
			]
		},
		"V": {
			"description": "foo",
			"export_functions": [
				{
					"name": "a",
					"description": "foo",
					"parameters": [
						{
							"name": "x",
							"type": {
								"name": "number"
							}
						}
					]
				},
				{
					"name": "b",
					"description": "foo",
					"parameters": [
						{
							"name": "x",
							"type": {
								"name": "number"
							}
						}
					]
				}
			]
		}
	},
	"classes": {
		"Box": {
			"description": "A heap allocated version of a type. Allows sharing of primitive types",
			"used_generics": [
				{
					"name": "$T"
				}
			],
			"methods": {
				"get": {
					"description": "Gets the inner item",
					"return_type": {
						"name": "$T"
					}
				}
			}
		},
		"Dict": {
			"description": "A dictionary",
			"used_generics": [
				{
					"name": "$K",
					"constraints": [
						"Hash"
					]
				},
				{
					"name": "$V"
				}
			],
			"methods": {
				"put": {
					"description": "Inserts a key and value into the dictionary",
					"parameters": [
						{
							"name": "key",
							"type": {
								"name": "$K"
							}
						},
						{
							"name": "value",
							"type": {
								"name": "$V"
							}
						}
					]
				}
			}
		},
		"Pair": {
			"description": "A pair of two different values",
			"used_generics": [
				{
					"name": "$T1"
				},
				{
					"name": "$T2"
				}
			],
			"methods": {
				"first": {
					"description": "Gets the first item from the pair",
					"return_type": {
						"name": "$T1"
					}
				},
				"second": {
					"description": "Gets the second item from the pair",
					"return_type": {
						"name": "$T2"
					}
				}
			}
		},
		"Utils": {
			"description": "Asserts.",
			"static_methods": {
				"fail": {
					"description": "foo",
					"return_type": {
						"name": "bool"
					}
				}
			},
			"methods": {
				"assert_state_is_not_null": {
					"description": "Asserts state is not null."
				},
				"call_on_b_fn": {
					"description": "Calls its own on_b function."
				},
				"cause_game_fn_error": {
					"description": "Causes a game fn error."
				},
				"cause_game_fn_error_generic": {
					"description": "accepts a generic value and unconditionally causes a runtime error",
					"used_generics": [
						{
							"name": "$T"
						}
					],
					"return_type": {
						"name": "bool"
					},
					"parameters": [
						{
							"name": "input",
							"type": {
								"name": "$T"
							}
						}
					]
				}
			}
		},
		"Vec": {
			"description": "A vector",
			"used_generics": [
				{
					"name": "$T"
				}
			],
			"static_methods": {
				"new": {
					"description": "Creates a new empty Vec.",
					"return_type": {
						"name": "Vec",
						"generics": [
							{
								"name": "$T"
							}
						]
					},
					"parameters": []
				}
			},
			"methods": {
				"insert": {
					"description": "Inserts an element at index i",
					"parameters": [
						{
							"name": "index",
							"type": {
								"name": "number"
							}
						},
						{
							"name": "value",
							"type": {
								"name": "$T"
							}
						}
					]
				},
				"pop": {
					"description": "Removes the last element from the list and returns it",
					"return_type": {
						"name": "$T"
					},
					"parameters": []
				},
				"push": {
					"description": "Pushes an item to the end of the list",
					"parameters": [
						{
							"name": "value",
							"type": {
								"name": "$T"
							}
						}
					]
				}
			}
		},
		"VecNumber": {
			"description": "A growable list of numbers.",
			"static_methods": {
				"new": {
					"description": "Creates a new empty VecNumber.",
					"return_type": {
						"name": "VecNumber"
					},
					"parameters": []
				},
				"with_capacity": {
					"description": "Creates a new empty VecNumber with a minimum capacity.",
					"return_type": {
						"name": "VecNumber"
					},
					"parameters": [
						{
							"name": "capacity",
							"type": {
								"name": "number"
							}
						}
					]
				}
			},
			"methods": {
				"insert": {
					"description": "Inserts a value at an index.",
					"parameters": [
						{
							"name": "index",
							"type": {
								"name": "number"
							}
						},
						{
							"name": "value",
							"type": {
								"name": "number"
							}
						}
					]
				},
				"pop": {
					"description": "Removes the last element from the list and returns it",
					"return_type": {
						"name": "number"
					},
					"parameters": []
				},
				"push": {
					"description": "Pushes a number to the end of the list.",
					"parameters": [
						{
							"name": "value",
							"type": {
								"name": "number"
							}
						}
					]
				}
			}
		}
	},
	"host_functions": {
		"assert_state_is_not_null": {
			"description": "foo"
		},
		"blocked_alrm": {
			"description": "foo"
		},
		"box": {
			"description": "Creates a boxed item",
			"used_generics": [
				{
					"name": "$T"
				}
			],
			"return_type": {
				"name": "Box",
				"generics": [
					{
						"name": "$T"
					}
				]
			},
			"parameters": [
				{
					"name": "item",
					"type": {
						"name": "$T"
					}
				}
			]
		},
		"box_number": {
			"description": "foo",
			"return_type": {
				"name": "BoxedNumber"
			},
			"parameters": [
				{
